name: Build and Deploy to GCS

on:
  push:
    branches:
      - main  # Change this to your main branch name
      - build-push-workflow

env:
  GCS_BUCKET: cortex-bucket-24

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Change to your preferred Node.js version

      - name: Install Dependencies
        run: npm install # Or yarn install, depending on your setup

      - name: Build React App
        run: npm run build # Replace with your build command

      - name: Set Up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Upload to GCS
        run: |
          gsutil -m rsync -r -d build gs://$GCS_BUCKET/
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}







